# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cypher/.eric6/eric6plugins/ProjectDjango/ConfigurationPage/DjangoPage.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DjangoPage(object):
    def setupUi(self, DjangoPage):
        DjangoPage.setObjectName("DjangoPage")
        DjangoPage.resize(536, 1201)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(DjangoPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.headerLabel = QtWidgets.QLabel(DjangoPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_6.addWidget(self.headerLabel)
        self.line15 = QtWidgets.QFrame(DjangoPage)
        self.line15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line15.setObjectName("line15")
        self.verticalLayout_6.addWidget(self.line15)
        self.djangoConsoleGroup = QtWidgets.QGroupBox(DjangoPage)
        self.djangoConsoleGroup.setObjectName("djangoConsoleGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.djangoConsoleGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.djangoConsoleGroup)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.consoleCommandCombo = QtWidgets.QComboBox(self.djangoConsoleGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleCommandCombo.sizePolicy().hasHeightForWidth())
        self.consoleCommandCombo.setSizePolicy(sizePolicy)
        self.consoleCommandCombo.setEditable(True)
        self.consoleCommandCombo.setObjectName("consoleCommandCombo")
        self.gridLayout.addWidget(self.consoleCommandCombo, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.djangoConsoleGroup)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.consoleCommandNoCloseCombo = QtWidgets.QComboBox(self.djangoConsoleGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleCommandNoCloseCombo.sizePolicy().hasHeightForWidth())
        self.consoleCommandNoCloseCombo.setSizePolicy(sizePolicy)
        self.consoleCommandNoCloseCombo.setEditable(True)
        self.consoleCommandNoCloseCombo.setObjectName("consoleCommandNoCloseCombo")
        self.gridLayout.addWidget(self.consoleCommandNoCloseCombo, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.djangoConsoleGroup)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.verticalLayout_6.addWidget(self.djangoConsoleGroup)
        self.djangoServerGroup = QtWidgets.QGroupBox(DjangoPage)
        self.djangoServerGroup.setObjectName("djangoServerGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.djangoServerGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.djangoServerGroup)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.serverAddressEdit = QtWidgets.QLineEdit(self.djangoServerGroup)
        self.serverAddressEdit.setObjectName("serverAddressEdit")
        self.gridLayout_2.addWidget(self.serverAddressEdit, 0, 1, 1, 1)
        self.ipv6CheckBox = QtWidgets.QCheckBox(self.djangoServerGroup)
        self.ipv6CheckBox.setObjectName("ipv6CheckBox")
        self.gridLayout_2.addWidget(self.ipv6CheckBox, 1, 0, 1, 2)
        self.verticalLayout_6.addWidget(self.djangoServerGroup)
        self.djangoBrowserGroup = QtWidgets.QGroupBox(DjangoPage)
        self.djangoBrowserGroup.setObjectName("djangoBrowserGroup")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.djangoBrowserGroup)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.externalBrowserCheckBox = QtWidgets.QCheckBox(self.djangoBrowserGroup)
        self.externalBrowserCheckBox.setObjectName("externalBrowserCheckBox")
        self.verticalLayout_5.addWidget(self.externalBrowserCheckBox)
        self.verticalLayout_6.addWidget(self.djangoBrowserGroup)
        self.djangoRecentAppsGroup = QtWidgets.QGroupBox(DjangoPage)
        self.djangoRecentAppsGroup.setObjectName("djangoRecentAppsGroup")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.djangoRecentAppsGroup)
        self.vboxlayout.setContentsMargins(6, 6, 6, 6)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self._2 = QtWidgets.QHBoxLayout()
        self._2.setObjectName("_2")
        self.label_4 = QtWidgets.QLabel(self.djangoRecentAppsGroup)
        self.label_4.setObjectName("label_4")
        self._2.addWidget(self.label_4)
        self.appsRecentSpinBox = QtWidgets.QSpinBox(self.djangoRecentAppsGroup)
        self.appsRecentSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.appsRecentSpinBox.setMinimum(5)
        self.appsRecentSpinBox.setMaximum(50)
        self.appsRecentSpinBox.setObjectName("appsRecentSpinBox")
        self._2.addWidget(self.appsRecentSpinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._2.addItem(spacerItem)
        self.vboxlayout.addLayout(self._2)
        self.verticalLayout_6.addWidget(self.djangoRecentAppsGroup)
        self.python3Group = QtWidgets.QGroupBox(DjangoPage)
        self.python3Group.setObjectName("python3Group")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.python3Group)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.djangoVirtualEnvPy3Group = QtWidgets.QGroupBox(self.python3Group)
        self.djangoVirtualEnvPy3Group.setObjectName("djangoVirtualEnvPy3Group")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.djangoVirtualEnvPy3Group)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.djangoVirtualEnvPy3Group)
        self.label_6.setMinimumSize(QtCore.QSize(0, 40))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 2)
        self.virtualEnvPy3Edit = QtWidgets.QLineEdit(self.djangoVirtualEnvPy3Group)
        self.virtualEnvPy3Edit.setObjectName("virtualEnvPy3Edit")
        self.gridLayout_4.addWidget(self.virtualEnvPy3Edit, 1, 0, 1, 1)
        self.virtualEnvPy3Button = QtWidgets.QToolButton(self.djangoVirtualEnvPy3Group)
        self.virtualEnvPy3Button.setObjectName("virtualEnvPy3Button")
        self.gridLayout_4.addWidget(self.virtualEnvPy3Button, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.djangoVirtualEnvPy3Group)
        self.djangoPython3Group = QtWidgets.QGroupBox(self.python3Group)
        self.djangoPython3Group.setObjectName("djangoPython3Group")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.djangoPython3Group)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainPython3CheckBox = QtWidgets.QCheckBox(self.djangoPython3Group)
        self.plainPython3CheckBox.setObjectName("plainPython3CheckBox")
        self.verticalLayout.addWidget(self.plainPython3CheckBox)
        self.verticalLayout_4.addWidget(self.djangoPython3Group)
        self.verticalLayout_6.addWidget(self.python3Group)
        self.python2Group = QtWidgets.QGroupBox(DjangoPage)
        self.python2Group.setObjectName("python2Group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.python2Group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.djangoVirtualEnvPy2Group = QtWidgets.QGroupBox(self.python2Group)
        self.djangoVirtualEnvPy2Group.setObjectName("djangoVirtualEnvPy2Group")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.djangoVirtualEnvPy2Group)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.djangoVirtualEnvPy2Group)
        self.label_7.setMinimumSize(QtCore.QSize(0, 40))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 2)
        self.virtualEnvPy2Edit = QtWidgets.QLineEdit(self.djangoVirtualEnvPy2Group)
        self.virtualEnvPy2Edit.setObjectName("virtualEnvPy2Edit")
        self.gridLayout_5.addWidget(self.virtualEnvPy2Edit, 1, 0, 1, 1)
        self.virtualEnvPy2Button = QtWidgets.QToolButton(self.djangoVirtualEnvPy2Group)
        self.virtualEnvPy2Button.setObjectName("virtualEnvPy2Button")
        self.gridLayout_5.addWidget(self.virtualEnvPy2Button, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.djangoVirtualEnvPy2Group)
        self.djangoPython2Group = QtWidgets.QGroupBox(self.python2Group)
        self.djangoPython2Group.setObjectName("djangoPython2Group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.djangoPython2Group)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainPython2CheckBox = QtWidgets.QCheckBox(self.djangoPython2Group)
        self.plainPython2CheckBox.setObjectName("plainPython2CheckBox")
        self.verticalLayout_2.addWidget(self.plainPython2CheckBox)
        self.verticalLayout_3.addWidget(self.djangoPython2Group)
        self.verticalLayout_6.addWidget(self.python2Group)
        self.TranslationsGroup = QtWidgets.QGroupBox(DjangoPage)
        self.TranslationsGroup.setObjectName("TranslationsGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TranslationsGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.TranslationsGroup)
        self.label_8.setMinimumSize(QtCore.QSize(0, 40))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 2)
        self.translationsEdit = QtWidgets.QLineEdit(self.TranslationsGroup)
        self.translationsEdit.setObjectName("translationsEdit")
        self.gridLayout_3.addWidget(self.translationsEdit, 1, 0, 1, 1)
        self.translationsButton = QtWidgets.QToolButton(self.TranslationsGroup)
        self.translationsButton.setObjectName("translationsButton")
        self.gridLayout_3.addWidget(self.translationsButton, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.TranslationsGroup)
        spacerItem1 = QtWidgets.QSpacerItem(20, 274, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)

        self.retranslateUi(DjangoPage)
        QtCore.QMetaObject.connectSlotsByName(DjangoPage)
        DjangoPage.setTabOrder(self.consoleCommandCombo, self.consoleCommandNoCloseCombo)
        DjangoPage.setTabOrder(self.consoleCommandNoCloseCombo, self.serverAddressEdit)
        DjangoPage.setTabOrder(self.serverAddressEdit, self.ipv6CheckBox)
        DjangoPage.setTabOrder(self.ipv6CheckBox, self.externalBrowserCheckBox)
        DjangoPage.setTabOrder(self.externalBrowserCheckBox, self.appsRecentSpinBox)
        DjangoPage.setTabOrder(self.appsRecentSpinBox, self.virtualEnvPy3Edit)
        DjangoPage.setTabOrder(self.virtualEnvPy3Edit, self.virtualEnvPy3Button)
        DjangoPage.setTabOrder(self.virtualEnvPy3Button, self.plainPython3CheckBox)
        DjangoPage.setTabOrder(self.plainPython3CheckBox, self.virtualEnvPy2Edit)
        DjangoPage.setTabOrder(self.virtualEnvPy2Edit, self.virtualEnvPy2Button)
        DjangoPage.setTabOrder(self.virtualEnvPy2Button, self.plainPython2CheckBox)
        DjangoPage.setTabOrder(self.plainPython2CheckBox, self.translationsEdit)
        DjangoPage.setTabOrder(self.translationsEdit, self.translationsButton)

    def retranslateUi(self, DjangoPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("DjangoPage", "<b>Configure Django</b>"))
        self.djangoConsoleGroup.setTitle(_translate("DjangoPage", "Console Commands"))
        self.label.setText(_translate("DjangoPage", "Console Command:"))
        self.consoleCommandCombo.setToolTip(_translate("DjangoPage", "Enter the console command"))
        self.label_2.setText(_translate("DjangoPage", "Console Command (non-closing):"))
        self.consoleCommandNoCloseCombo.setToolTip(_translate("DjangoPage", "Enter the console command for a non-closing console"))
        self.label_5.setText(_translate("DjangoPage", "<b>Note:</b> The console command for a console, that is spawning (i.e. exits before the console window is closed), should be prefixed by an \'@\' character."))
        self.djangoServerGroup.setTitle(_translate("DjangoPage", "Server"))
        self.label_3.setText(_translate("DjangoPage", "Server Address:"))
        self.serverAddressEdit.setToolTip(_translate("DjangoPage", "Enter the server port or server address and port (e.g. 127.0.0.1:8000 or [::1]:8000)"))
        self.ipv6CheckBox.setToolTip(_translate("DjangoPage", "Select to use IPv6"))
        self.ipv6CheckBox.setText(_translate("DjangoPage", "Use IPv6 protocol"))
        self.djangoBrowserGroup.setTitle(_translate("DjangoPage", "Web-Browser"))
        self.externalBrowserCheckBox.setToolTip(_translate("DjangoPage", "Select to use an external web-browser"))
        self.externalBrowserCheckBox.setText(_translate("DjangoPage", "Use external web-browser"))
        self.djangoRecentAppsGroup.setTitle(_translate("DjangoPage", "Recent Applications Lists"))
        self.label_4.setText(_translate("DjangoPage", "Number of recent applications lists:"))
        self.appsRecentSpinBox.setToolTip(_translate("DjangoPage", "Enter the number of recent applications to remember"))
        self.python3Group.setTitle(_translate("DjangoPage", "Python 3"))
        self.djangoVirtualEnvPy3Group.setTitle(_translate("DjangoPage", "Django Virtual Environment"))
        self.label_6.setText(_translate("DjangoPage", "Enter the path of the Django virtual environment. Leave empty to not use a virtual environment setup."))
        self.virtualEnvPy3Button.setToolTip(_translate("DjangoPage", "Select the virtual environment directory via a selection dialog"))
        self.djangoPython3Group.setTitle(_translate("DjangoPage", "Django Python Console"))
        self.plainPython3CheckBox.setToolTip(_translate("DjangoPage", "Select to use plain Python instead of IPython"))
        self.plainPython3CheckBox.setText(_translate("DjangoPage", "Use plain Python instead of IPython"))
        self.python2Group.setTitle(_translate("DjangoPage", "Python 2"))
        self.djangoVirtualEnvPy2Group.setTitle(_translate("DjangoPage", "Django Virtual Environment"))
        self.label_7.setText(_translate("DjangoPage", "Enter the path of the Django virtual environment. Leave empty to not use a virtual environment setup."))
        self.virtualEnvPy2Button.setToolTip(_translate("DjangoPage", "Select the virtual environment directory via a selection dialog"))
        self.djangoPython2Group.setTitle(_translate("DjangoPage", "Django Python Console"))
        self.plainPython2CheckBox.setToolTip(_translate("DjangoPage", "Select to use plain Python instead of IPython"))
        self.plainPython2CheckBox.setText(_translate("DjangoPage", "Use plain Python instead of IPython"))
        self.TranslationsGroup.setTitle(_translate("DjangoPage", "Translations Editor"))
        self.label_8.setText(_translate("DjangoPage", "Enter the path of an editor to use to do the translations. Leave empty to disable this feature."))
        self.translationsButton.setToolTip(_translate("DjangoPage", "Select the translations editor via a file selection dialog"))

